# Generated by Django 3.2.8 on 2022-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pos_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
    ]
