# Generated by Django 3.2.8 on 2022-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pos_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
